version: "3"
services:
  app:
    build: .
    restart: on-failure
    links:
      - db
    ports:
      - 8000:8000

  db:
    image: mysql:8.0.22
    ports:
      - 30000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
